### ISSUE TITLE
no way to use it in ArcGIS Pro ?

### ISSUE THREAD

**Issue by laurentwww** [Esri/public-transit-tools#116]
Is there any way to use GTFS tools in ArcGIS Pro ? I only have this version.

Regards.

**Comment by mmorang** [comment]
All of the tools in this repo work in ArcGIS Pro _except_ Add GTFS to a Network Dataset.  Add GTFS to a Network Dataset is not supported in Pro because it uses a "custom evaluator" built in ArcObjects, and Pro's SDK does not allow you to create or use a custom evaluator.

Which tool, specifically, are you having problems with?

**Comment by mmorang** [comment]
I have created a new issue to add support for Add GTFS to a Network Dataset in Pro, mostly so people like you can up-vote it and explain your use case.  This will help me to advocate for support internally at Esri to get this functionality implemented.  Thanks.
https://github.com/Esri/public-transit-tools/issues/117
