### ISSUE TITLE
Create Shapes with Network Dataset gets stuck on loop, never creates the shapes.

### ISSUE THREAD

**Issue by Potatoroid** [Esri/public-transit-tools#123]
When using network analyst to create GTFS steps <img width="473" alt="gtfs_settings" src="https://user-images.githubusercontent.com/40771282/42183660-5636e02c-7e08-11e8-942f-3336dd6afd7c.png">, the tool appears to get stuck on one of the steps and never creates the completed shapes. <img width="541" alt="gtfs_steps" src="https://user-images.githubusercontent.com/40771282/42183674-5f867430-7e08-11e8-9f6b-da12c9a454f6.png"> This issue has no occurred when trying to create the GTFS shapes with straight lines. My question: Is this a problem with the tool or the network dataset? My hunch is that the network dataset has flaws that are messing up the tool, as around 500 of the 11000 stops were not able to be used in service area analysis ("Warning: Location "Location 10618" in "Facilities" is on a non-traversable network element position."). Any help on this would be appreciated.

**Comment by mmorang** [comment]
Yes, it sounds like the problem is related to the Network Analyst portion of the process.  If your network dataset is poorly connected, then sometimes what happens is for every route, it has to search the entire network only to determine that there is no route, and that takes a lot of time.  Have you been able to successfully use this network dataset for anything else?  Try creating some tests routes and service areas with the network manually, separate from this tool.  If you're uncertain of how to do that, check out the [Network Analyst tutorials](http://desktop.arcgis.com/en/arcmap/latest/extensions/network-analyst/about-the-network-analyst-tutorial-exercises.htm).

**Comment by mmorang** [comment]
@Potatoroid Did you ever resolve this problem?

**Comment by mmorang** [comment]
Closing this issue due to lack of response.  Please re-open if you're still having the problem and need more help.
