### ISSUE TITLE
Error when running Calculate Accessibility Matrix

### ISSUE THREAD

**Issue by ritafan720** [Esri/public-transit-tools#149]
I have been getting the same error message when I run the Calculate Accessibility Matrix.

1900-01-03 08:50:00
Sove failed. Errors: ERROR 030024: Solve returned a failure.
Insufficient number of valid locations in "Origins" or "Destinations".
Failed to execute (Solve).
. Continuing to next time of day.
1900-01-03 08:55:00
Sove failed. Errors: ERROR 030024: Solve returned a failure.
Insufficient number of valid locations in "Origins" or "Destinations".
Failed to execute (Solve).
. Continuing to next time of day.
1900-01-03 09:00:00
Sove failed. Errors: ERROR 030024: Solve returned a failure.
Insufficient number of valid locations in "Origins" or "Destinations".
Failed to execute (Solve).
. Continuing to next time of day.
Calculating statistics and writing results...
Done! Statistics fields have been added to your input Origins layer.
Completed script CalculateAccessibilityMatrix...

I tried to change my Origins and Destinations several times and it just doesn’t work. However, if I am using the same Origins and Destinations to solve OD Cost Matrix it did give my result.

Does anyone know what problem would it be?

Thanks.

**Comment by mmorang** [comment]
Hello. The most likely problem is that your input Origins or Destinations cannot locate properly on the network dataset.  Maybe they aren't in the same geographic area as your network, or they are really far away or something.

When you say it worked when you used the same Origins and Destinations, which of your original inputs were you using?  In other words, if you used your original Origins for both Origins and Destinations, and that worked, then it's likely that the problem lies in your original Destinations.

Have you tried adding your Origins and Destinations to your OD Cost Matrix layer and just solving it the normal way?  Don't use the Calculate Accessibility Matrix. First just make sure the OD Cost Matrix layer works the way you want it to. Once you have that working, _then_ run the tool.

Without further details about your problem and your input data, it's kind of hard to diagnose.

**Comment by ritafan720** [comment]
Hi mmorang,

Thanks a lot for your response.

I have tried to add my Origins and Destinations to my OD Cost Matrix layer and solved it. It run successfully. However, when I use the same pairs of Origins and Destinations (that I used to solve OD Cost Matrix the normal way) to run the Calculate Accessibility Matrix tool, it fails and still is giving me the same message.

**Comment by mmorang** [comment]
Okay, sounds like something is still wrong, but I don't have enough information to diagnose the problem.  Can you add more details?  For example:
1) Are you using ArcMap or ArcGIS Pro, and which version?
2) Can you leave a screenshot of your set-up of the Calculate Accessibility Matrix tool so I can tell what you're putting into it?
3) Can you list the properties of your OD Cost Matrix layer or post a screenshot?

I don't think this will necessarily answer the question, but at least we'll be working toward an answer.

**Comment by ritafan720** [comment]
I am on ArcGIS Desktop 10.6.1.

Screenshot of the set-up the Calculate Accessibility Matrix tool: 
![image](https://user-images.githubusercontent.com/75644340/101419361-f327dc80-3943-11eb-993e-0ef9727deca3.png)

The properties of my OD Cost Matrix layre: 
![image](https://user-images.githubusercontent.com/75644340/101419168-975d5380-3943-11eb-9750-7efe1f1a5bff.png)
![image](https://user-images.githubusercontent.com/75644340/101419419-105cab00-3944-11eb-8b20-364f6e4cdf52.png)
![image](https://user-images.githubusercontent.com/75644340/101419451-266a6b80-3944-11eb-8be1-f434c69a6be7.png)

**Comment by mmorang** [comment]
Ohhhhh, okay.

For the Origins and Destinations inputs to the Calculate Accessibility Matrix tool, you need to pass in the feature class or layer you to want to use, rather than the Origins and Destinations sublayers of the OD Cost Matrix Layer itself.  The tool will run Add Locations to add the origins and destinations to the sublayers.  The way you have it set up now, it's trying to add itself to itself...or something like that.  My guess is it adds nothing and then complains about it.

So, if your origins are located at C:\Data\ODAnalysis.gdb\Origins, use that path as the Origins input in Calculate Accessibility Matrix.

**Comment by ritafan720** [comment]
Ohhhhhh it is working now!

The problem is that I didn't use a feature class or layer for Origins and Destinations. 

Thanks for solving my issue!
