### ISSUE TITLE
Calculate Accessibility Matrix and Calculate Travel Time Statistics : Type Error 

### ISSUE THREAD

**Issue by Pranav-Gairola** [Esri/public-transit-tools#150]
<img width="928" alt="Traceback_shot" src="https://user-images.githubusercontent.com/51087815/107847823-da8ce480-6e14-11eb-81db-13cc0d3aba1c.png">

I Don't know what to do with this error or the source of this error. Any suggestion would be really helpful.

**Comment by mmorang** [comment]
It looks like the tool's validation is freaking out about something. It is likely a bug.

 Can you tell me what version of ArcMap you're using? I will see if I can reproduce the problem and fix it.

**Comment by Pranav-Gairola** [comment]
Thanks for your reply. I am using Arcmap version 10.5.

Pranav Gairola
Research Scholar
Department of Civil Engineering
Indian Institute of Technology Delhi
New Delhi-110016

**Comment by mmorang** [comment]
Hmm.  I cannot reproduce this problem in ArcMap 10.8.1, which is what I have installed right now.  I can spin up a machine with 10.5 if needed.  However, I remembered that another user encountered a similar problem before when running the tool in ArcGIS Pro, which makes me think the problem is not version specific.

https://community.esri.com/t5/arcgis-for-public-transit/calculate-accessibility-matrix-error/m-p/447796

I could not reproduce the problem at that time either, and my best guess was that the user also had the BetterBusBuffers tool saved somewhere on their machine. BetterBusBuffers also has a function called allow_YYYYMMDD_day(), and it's almost as if the two tools are getting mixed up about whose function to call. I really have no idea how that would happen. My best idea at this point is for you to delete both BetterBusBuffers and Transit Analysis Tools from your machine, re-download them, and make sure they are saved to completely different folders.

Let me know if that helps...?

**Comment by mmorang** [comment]
(If you do, in fact, have both of these tools on your machine currently, it would help me to know how/where you have them saved so maybe I can finally reproduce the problem and fix it.)

**Comment by Pranav-Gairola** [comment]
Yes, Initially I had BetterBusBuffers in the same place with Transit-Network-Analysis-Tool. But I had already gone through this thread you are referring to and I re-installed both the tools and placed them in different folders of my PC.

**Comment by Pranav-Gairola** [comment]
Looks like you were right. Now when i closed my ArcMap and re-open it and  the tool seems to be working alright. Thanks for your help. I Really appreciate this.

**Comment by mmorang** [comment]
That's very weird.  I...still don't really understand what happened, but I'm glad it's working now.

**Comment by Pranav-Gairola** [comment]
Probably you were right about mixing up of these tools in calling the same named function. As soon as I changed the directory of these tools, re-installed both tools and restart ArcMap, it worked like magic. 
Thanks again!
