### ISSUE TITLE
Barriers in OD public transit accessibility matrix 

### ISSUE THREAD

**Issue by yalabbad** [Esri/public-transit-tools#191]
First, thanks for the great tool. 

I have a question about the barriers in the OD Cost Matrix analysis (public transit). How does it work? 
For example, if a street segment is a barrier or a bus stop within a polygon barrier, can a bus drive on/to it? How does the model find alternative routes to reach a destination?

Thanks

**Comment by mmorang** [comment]
Sure thing.

This documentation explains all about barriers: https://pro.arcgis.com/en/pro-app/latest/help/analysis/networks/barriers.htm

The one thing that page doesn't really describe is what happens if an origin or destination is on a street that's restricted by a barrier.  In that case, the point will locate on the nearest unrestricted location, and the route will navigate to that location, getting as close as possible to the original point.  Some information about locating is in this documentation: https://pro.arcgis.com/en/pro-app/latest/help/analysis/networks/locating-analysis-inputs.htm

For transit analyses specifically, you need to be pretty careful about how you use barriers.  You should not use barriers to obstruct transit lines. If a barrier blocks one transit line segment, the solver is not smart enough to know that the transit line segments further on will also be delayed or not running. Each transit line segment just checks to see what the schedule is and uses it without regard for anything that may have happened upstream.

Instead, if you want to turn service on and off for a particular line, trip, mode, etc., you can do this using the special parameters available with the Public Transit evaluator described here: https://pro.arcgis.com/en/pro-app/latest/help/analysis/networks/public-transit-evaluator.htm#ESRI_SECTION1_9FF9489173C741DD95472F21B5AD8374  [This video](https://youtu.be/fBbIMTWzDYg?t=1202) may also be helpful.

With all that said, barriers are perfectly valid to use for blocking pedestrian areas or streets. Just don't put them on transit lines.

**Comment by yalabbad** [comment]
@mmorang  Thank you for the quick response and for providing useful resources. You said, "If a barrier blocks one transit line segment, ...", do you mean that the barriers should not be placed on the line variant element layer? Can you explain more? Thanks

**Comment by mmorang** [comment]
Yes, that's correct.  Avoid putting barriers on a LineVariantElements feature because that feature will be blocked, but all the ones downstream will not be adjusted.

**Comment by mmorang** [comment]
Closing this issue, since I assume I answered the question.
